name: 'Setup Cask'
description: 'Install a specific Cask version for use in your workflow.'
author: 'Naoya Yamashita'
inputs:
  version:
    description: 'The version of Cask to install, e.g. "0.8.4", or "snapshot" for a recent development version.'
    default: 'snapshot'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'code'
  color: 'yellow'
